GET https://api.nbp.pl/api/exchangerates/tables/B/2002-01-02/2002-03-31?format=json
Accept: application/json
###

GET https://api.nbp.pl/api/exchangerates/tables/B/2002-04-01/2002-06-30?format=json
Accept: application/json
###

GET https://api.nbp.pl/api/exchangerates/tables/B/2009-01-01/2009-03-31?format=json
Accept: application/json
###

2-09-30?format=json
Accept: application/json
###

GET https://api.nbp.pl/api/exchangerates/tables/B/2002-10-01/2002-12-31?format=json
Accept: application/json
###




# GET https://api.nbp.pl/api/exchangerates/tables/A/2015-01-01/2015-03-31?format=json


GET https://api.nbp.pl/api/exchangerates/tables/B/2002-01-01/2002-01-03?format=json
Accept: application/json
###

GET https://api.nbp.pl/api/exchangerates/tables/A/2025-01-01/2025-01-03?format=json
Accept: application/json
###